### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by sxdeivm** [zhysora/UCGAN#1]
请问这个错误应该怎么解决呢，“main.py: error: the following arguments are required: -c/--config”

**Comment by zhysora** [comment]
你需要给main.py传一个配置文件
python main.py -c configs/ucgan.py

**Comment by sxdeivm** [comment]
请问这个错误也是传一样的配置文件吗？“tif2png.py: error: the following arguments are required: -s/--src_file”




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/UCGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/UCGAN] 问题 (Issue #1)





 
你需要给main.py传一个配置文件
 python main.py -c configs/ucgan.py

**Comment by zhysora** [comment]
这个是缺少参数-s，需要传入待转换的.tif图像

发自我的iPhone

**Comment by sxdeivm** [comment]
这个代码运行的融合之后结果在哪看呀，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/UCGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/UCGAN] 问题 (Issue #1)





 这个是缺少参数-s，需要传入待转换的.tif图像
 
 发自我的iPhone
 
 &gt; 在 2022年7月8日，下午8:23，sxdeivm ***@***.***&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; 请问这个错误也是传一样的配置文件吗？“tif2png.py: error: the following arguments are required: -s/--src_file” 
 &gt; 
 &gt; 
 &gt; 
 &gt; 
 &gt; ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 &gt; 发件人: "zhysora/UCGAN" ***@***.***&amp;gt;; 
 &gt; 发送时间:&amp;nbsp;2022年7月8日(星期五) 下午5:08 
 &gt; ***@***.***&amp;gt;; 
 &gt; ***@***.******@***.***&amp;gt;; 
 &gt; 主题:&amp;nbsp;Re: [zhysora/UCGAN] 问题 (Issue #1) 
 &gt; 
 &gt; 
 &gt; 
 &gt; 
 &gt; 
 &gt; 
 &gt; 你需要给main.py传一个配置文件 
 &gt; python main.py -c configs/ucgan.py 
 &gt; 
 &gt; — 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt;
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you commented.

**Comment by zhysora** [comment]
根据config文件，会放在work_dir内
