### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by kechengjie** [zhysora/UCGAN#3]
输入保持与原始遥感图像相同的比特深度，无需任何其他预处理，请问这句话是什么意思呢，是指输入图像不经过归一化，按原始比特位输入吗

**Comment by zhysora** [comment]
是的

发自我的iPhone

**Comment by kechengjie** [comment]
那如果复现您的代码时，把多光谱、全色归一化再输入到网络，结果会有影响吗

**Comment by zhysora** [comment]
如果从头训练的话应该影响不大

发自我的iPhone

**Comment by kechengjie** [comment]
好的，谢谢您！
