### ISSUE TITLE
question about the training data

### ISSUE THREAD

**Issue by liujinyang1** [zhysora/UCGAN#4]
Could you please provide links to all training data and test data, this will be of great help to our research, thank you.

**Comment by zhysora** [comment]
link: https://pan.baidu.com/s/190MywbwIlvONA_9-6-KMtQ code: u041
link: https://pan.baidu.com/s/1dRrMH6KcFnkGuYZMCcJooA code: odg0

**Comment by zhysora** [comment]
the data pre-processing is similar to https://github.com/zhysora/PGMAN

**Comment by liujinyang1** [comment]
thank you very much, best wishes
