### ISSUE TITLE
测试数据test data问题

### ISSUE THREAD

**Issue by eleveneee** [zhysora/UCGAN#8]
我对测试数据有一些疑问，想请教一下您，并且非常期待等您的回复：
（1）test_full_res：大尺度
0_lr.tif：多光谱？
0_lr_u.tif：？
0_pan.tif：全色
（2）test_low_res：小尺度
0_lr.tif：多光谱？
0_lr_u.tif：？
0_mul.tif：多光谱
0_pan.tif：全色

打问号的地方是我不清楚的，不知道具体代表的是什么类型的影像数据，非常期待您的回复！谢谢！

**Comment by zhysora** [comment]
0_lr.tif 是输入的多光谱图像，非GT
0_mul.tif 是GT多光谱图像
0_lr_u.tif 是 0_lr.tif的上采样，采样到和0_pan.tif的宽高一致。

**Comment by eleveneee** [comment]
非常感谢！！

**Comment by eleveneee** [comment]
您好，再次打扰，请问test_full_res和test_low_res文件夹是分别对应高分辨率和低分辨率影像吗？
谢谢！
@zhysora
